-- Schema PostgreSQL para a aplicação No Meu Ritmo!
-- Cria as tabelas principais: matérias, plano de estudos e sessões registradas.

BEGIN;

CREATE TYPE prioridade_materia AS ENUM ('baixa', 'media', 'alta');
CREATE TYPE tipo_estudo AS ENUM ('leitura', 'revisao', 'exercicios', 'projeto');
CREATE TYPE status_plano AS ENUM ('planejado', 'em_andamento', 'concluido', 'cancelado');

CREATE TABLE materias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL UNIQUE,
    cor CHAR(7) NOT NULL DEFAULT '#2563eb',
    prioridade prioridade_materia NOT NULL DEFAULT 'media',
    descricao TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT materias_cor_hex_chk CHECK (cor ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE TABLE planos_estudo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia_id INTEGER NOT NULL REFERENCES materias(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    data_plano DATE NOT NULL DEFAULT CURRENT_DATE,
    horario TIME NOT NULL,
    tipo tipo_estudo NOT NULL,
    duracao_minutos INTEGER NOT NULL,
    meta TEXT NOT NULL,
    status status_plano NOT NULL DEFAULT 'planejado',
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT planos_estudo_duracao_chk CHECK (duracao_minutos BETWEEN 1 AND 1440),
    CONSTRAINT planos_estudo_horario_unico UNIQUE (data_plano, horario, materia_id)
);

CREATE TABLE sessoes_estudo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia_id INTEGER NOT NULL REFERENCES materias(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    tipo_estudo tipo_estudo NOT NULL,
    duracao_minutos INTEGER NOT NULL,
    nivel_foco INTEGER NOT NULL,
    observacao TEXT,
    data_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT sessoes_estudo_duracao_chk CHECK (duracao_minutos BETWEEN 1 AND 1440),
    CONSTRAINT sessoes_estudo_nivel_foco_chk CHECK (nivel_foco BETWEEN 1 AND 5)
);

CREATE INDEX idx_materias_prioridade ON materias (prioridade);
CREATE INDEX idx_planos_estudo_data ON planos_estudo (data_plano);
CREATE INDEX idx_planos_estudo_materia ON planos_estudo (materia_id);
CREATE INDEX idx_sessoes_estudo_data ON sessoes_estudo (data_registro);
CREATE INDEX idx_sessoes_estudo_materia ON sessoes_estudo (materia_id);

CREATE OR REPLACE FUNCTION atualizar_coluna_atualizado_em()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_materias_atualizado_em
BEFORE UPDATE ON materias
FOR EACH ROW
EXECUTE FUNCTION atualizar_coluna_atualizado_em();

CREATE TRIGGER trg_planos_estudo_atualizado_em
BEFORE UPDATE ON planos_estudo
FOR EACH ROW
EXECUTE FUNCTION atualizar_coluna_atualizado_em();

COMMIT;
