create table if not exists public.sessoes_estudo (
  id bigint generated by default as identity primary key,
  materia text not null,
  tipo_estudo text not null check (tipo_estudo in ('leitura', 'revisao', 'exercicios', 'projeto')),
  duracao_minutos integer not null check (duracao_minutos > 0 and duracao_minutos <= 300),
  nivel_foco integer not null check (nivel_foco >= 1 and nivel_foco <= 5),
  observacao text,
  data_registro date not null default current_date,
  created_at timestamptz not null default now()
);

alter table public.sessoes_estudo enable row level security;

drop policy if exists "Permitir leitura publica de sessoes" on public.sessoes_estudo;
create policy "Permitir leitura publica de sessoes"
on public.sessoes_estudo for select
to anon
using (true);

drop policy if exists "Permitir cadastro publico de sessoes" on public.sessoes_estudo;
create policy "Permitir cadastro publico de sessoes"
on public.sessoes_estudo for insert
to anon
with check (true);
