create table if not exists public.usuarios_app (
  id bigint generated by default as identity primary key,
  username text not null unique,
  senha_hash text not null,
  criado_em timestamptz not null default now()
);

create table if not exists public.materias (
  id bigint generated by default as identity primary key,
  usuario_id bigint references public.usuarios_app(id),
  nome text not null,
  cor text not null default '#2563eb'
    check (cor ~ '^#[0-9A-Fa-f]{6}$'),
  prioridade text not null default 'media'
    check (prioridade in ('baixa', 'media', 'alta')),
  descricao text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.planos_estudo (
  id bigint generated by default as identity primary key,
  usuario_id bigint references public.usuarios_app(id),
  materia_id bigint not null references public.materias(id) on update cascade on delete restrict,
  data_plano date not null default current_date,
  horario time not null,
  tipo text not null
    check (tipo in ('leitura', 'revisao', 'exercicios', 'projeto')),
  duracao_minutos integer not null
    check (duracao_minutos between 1 and 1440),
  meta text not null,
  status text not null default 'planejado'
    check (status in ('planejado', 'em_andamento', 'concluido', 'cancelado')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.sessoes_estudo (
  id bigint generated by default as identity primary key,
  usuario_id bigint references public.usuarios_app(id),
  materia_id bigint not null references public.materias(id) on update cascade on delete restrict,
  tipo_estudo text not null
    check (tipo_estudo in ('leitura', 'revisao', 'exercicios', 'projeto')),
  duracao_minutos integer not null
    check (duracao_minutos > 0 and duracao_minutos <= 300),
  nivel_foco integer not null
    check (nivel_foco >= 1 and nivel_foco <= 5),
  observacao text,
  data_registro date not null default current_date,
  criado_em timestamptz not null default now()
);

insert into public.usuarios_app (username, senha_hash)
values ('aluno', '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4')
on conflict (username) do nothing;

alter table public.materias
  add column if not exists usuario_id bigint references public.usuarios_app(id);

alter table public.sessoes_estudo
  add column if not exists usuario_id bigint references public.usuarios_app(id);

alter table public.planos_estudo
  add column if not exists usuario_id bigint references public.usuarios_app(id);

update public.materias
set usuario_id = (select id from public.usuarios_app where username = 'aluno')
where usuario_id is null;

update public.sessoes_estudo
set usuario_id = (select id from public.usuarios_app where username = 'aluno')
where usuario_id is null;

update public.planos_estudo
set usuario_id = (select id from public.usuarios_app where username = 'aluno')
where usuario_id is null;

alter table public.materias alter column usuario_id set not null;
alter table public.sessoes_estudo alter column usuario_id set not null;
alter table public.planos_estudo alter column usuario_id set not null;

alter table public.materias drop constraint if exists materias_nome_key;
create unique index if not exists materias_usuario_nome_key
  on public.materias (usuario_id, nome);
create index if not exists planos_estudo_usuario_id_idx
  on public.planos_estudo (usuario_id);
create index if not exists sessoes_estudo_usuario_id_idx
  on public.sessoes_estudo (usuario_id);

create or replace function public.atualizar_coluna_atualizado_em()
returns trigger as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_materias_atualizado_em on public.materias;
create trigger trg_materias_atualizado_em
before update on public.materias
for each row execute function public.atualizar_coluna_atualizado_em();

drop trigger if exists trg_planos_estudo_atualizado_em on public.planos_estudo;
create trigger trg_planos_estudo_atualizado_em
before update on public.planos_estudo
for each row execute function public.atualizar_coluna_atualizado_em();

alter table public.usuarios_app enable row level security;
alter table public.materias enable row level security;
alter table public.planos_estudo enable row level security;
alter table public.sessoes_estudo enable row level security;

drop policy if exists "Leitura publica usuarios app" on public.usuarios_app;
create policy "Leitura publica usuarios app"
on public.usuarios_app for select
to anon
using (true);

drop policy if exists "Cadastro publico usuarios app" on public.usuarios_app;
create policy "Cadastro publico usuarios app"
on public.usuarios_app for insert
to anon
with check (true);

drop policy if exists "Leitura publica materias" on public.materias;
create policy "Leitura publica materias"
on public.materias for select
to anon
using (true);

drop policy if exists "Cadastro publico materias" on public.materias;
create policy "Cadastro publico materias"
on public.materias for insert
to anon
with check (true);

drop policy if exists "Atualizacao publica materias" on public.materias;
create policy "Atualizacao publica materias"
on public.materias for update
to anon
using (true)
with check (true);

drop policy if exists "Exclusao publica materias" on public.materias;
create policy "Exclusao publica materias"
on public.materias for delete
to anon
using (true);

drop policy if exists "Leitura publica planos" on public.planos_estudo;
create policy "Leitura publica planos"
on public.planos_estudo for select
to anon
using (true);

drop policy if exists "Cadastro publico planos" on public.planos_estudo;
create policy "Cadastro publico planos"
on public.planos_estudo for insert
to anon
with check (true);

drop policy if exists "Atualizacao publica planos" on public.planos_estudo;
create policy "Atualizacao publica planos"
on public.planos_estudo for update
to anon
using (true)
with check (true);

drop policy if exists "Exclusao publica planos" on public.planos_estudo;
create policy "Exclusao publica planos"
on public.planos_estudo for delete
to anon
using (true);

drop policy if exists "Leitura publica sessoes" on public.sessoes_estudo;
create policy "Leitura publica sessoes"
on public.sessoes_estudo for select
to anon
using (true);

drop policy if exists "Cadastro publico sessoes" on public.sessoes_estudo;
create policy "Cadastro publico sessoes"
on public.sessoes_estudo for insert
to anon
with check (true);

drop policy if exists "Exclusao publica sessoes" on public.sessoes_estudo;
create policy "Exclusao publica sessoes"
on public.sessoes_estudo for delete
to anon
using (true);
