create table if not exists public.materias (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  cor text not null default '#2563eb'
    check (cor ~ '^#[0-9A-Fa-f]{6}$'),
  prioridade text not null default 'media'
    check (prioridade in ('baixa', 'media', 'alta')),
  descricao text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.sessoes_estudo (
  id bigint generated by default as identity primary key,
  materia_id bigint not null references public.materias(id) on update cascade on delete restrict,
  tipo_estudo text not null
    check (tipo_estudo in ('leitura', 'revisao', 'exercicios', 'projeto')),
  duracao_minutos integer not null
    check (duracao_minutos > 0 and duracao_minutos <= 300),
  nivel_foco integer not null
    check (nivel_foco >= 1 and nivel_foco <= 5),
  observacao text,
  data_registro date not null default current_date,
  criado_em timestamptz not null default now()
);

alter table public.materias enable row level security;
alter table public.sessoes_estudo enable row level security;

drop policy if exists "Leitura publica materias" on public.materias;
create policy "Leitura publica materias"
on public.materias for select
to anon
using (true);

drop policy if exists "Cadastro publico materias" on public.materias;
create policy "Cadastro publico materias"
on public.materias for insert
to anon
with check (true);

drop policy if exists "Atualizacao publica materias" on public.materias;
create policy "Atualizacao publica materias"
on public.materias for update
to anon
using (true)
with check (true);

drop policy if exists "Exclusao publica materias" on public.materias;
create policy "Exclusao publica materias"
on public.materias for delete
to anon
using (true);

drop policy if exists "Leitura publica sessoes" on public.sessoes_estudo;
create policy "Leitura publica sessoes"
on public.sessoes_estudo for select
to anon
using (true);

drop policy if exists "Cadastro publico sessoes" on public.sessoes_estudo;
create policy "Cadastro publico sessoes"
on public.sessoes_estudo for insert
to anon
with check (true);
